### ISSUE TITLE
improcess rewrite in python syntax

### ISSUE THREAD

**Issue by pv33** [ivapylibs/improcessor#1]
Most is there, just that I don't know how to use tuples.  Once I see it in action, I can figure it out.

I know that some of this code is more relevant to the hand, but I think it helps you to know what's up since we will be doing equivalent but more complex things with the background modeling to get the puzzle layer.

Something this simple should permit extraction of the robot layer.

**Comment by Uio96** [comment]
I have finished the translation work following your instruction in OneNote. It can fulfill the testing requirement. The original MATLAB function uses some official codes, e.g., imresize. Currently, I use the implementation from OpenCV instead. 

There is something minor that I am not sure how to do with. I put them in `FIXME` and `Todo` in `basic.py`. You can have a review.

**Comment by pv33** [comment]
@Uio96 
It looks to be highly specialized to only the functions that are in the conditional statements.  The original Matlab version could take in any function that was available in the calling scope, which is pretty much any default Matlab functions plus whatever could be found in the Matlab path.

If the function argument was a string, it used Matlab's ``feval`` to do so.
If the function argument was a function pointer, then it would just store the pointer and invoke the function.

I am not 100% clear on the python, but it seems like all functions need to be hard coded into a conditional processing statement when that should not be the case.  

According to google [search hit](http://people.bu.edu/andasari/courses/numericalpython/Week4Lecture7/example_feval.py), the equivalent to ``feval`` is

> eval(theFunc)(*args)

Thus, for the ``imresize`` example, the string should be "cv2.resize" and the function pointer argument would simply use the function pointer.  If the field ``theFunc`` is a function pointer, then it would be invoked via:

> theFunc(*args)

Please go back and modify the code to permit **any function** within the current scope to be permissible.

**Comment by pv33** [comment]
The exact same functionality in the Matlab version has not been reproduced. Correct for that to be the case.

**Comment by Uio96** [comment]
Got you. I know that we could use `eval` function but my current implementation with `getattr` is another choice for the class member function. 

So I think the exact same functionality in the Matlab version has already been reproduced. You can check my testing file.

**Comment by Uio96** [comment]
I have changed the implementation from `getattr` to `eval`.

**Comment by pv33** [comment]
@Uio96 
Impossible because line 130 explicitly has a check for imresize and uses ``cv.resize``.  If you truly did a general improcessor, then there would be absolutely no code involving any python functions in it.  I would be able to do a resize without ever seeing the explicitly named function ``cv.resize`` in the code for ``improcessor.basic``.

I should be able to change to invoke any function I care to that takes in an image. That is not the case in your code.  Your test script works but if I change it to invokve another OpenCV image processing function, it would fail.  For example, can I do Gaussian smoothing using your improcessor.basic?  Not from what I see.

You do not understand, or possibly have never used function pointers and string evaluation of arbitrary functions and don't seem to be getting it.

**Comment by pv33** [comment]
@Uio96 
The exact same implementation needs to be programmed. Lines 170-190 in the original ``improcessor_basic.m`` file are not reproduced and therefore all downstream parts are also going to be restricted. I will go look up things for you.

**Comment by Uio96** [comment]
Ok, I understand your points. I will update the code accordingly.

**Comment by pv33** [comment]
@Uio96 
Per original code, there is a test for a string or for a function pointer.

Test for string [here](https://www.geeksforgeeks.org/python-check-if-a-variable-is-string/).

For function handles/pointers, the situation is different.   See [here](https://stackoverflow.com/questions/624926/how-do-i-detect-whether-a-python-variable-is-a-function) and [here](https://stackoverflow.com/questions/2459329/how-to-determine-if-the-variable-is-a-function-in-python).  The original ``improcessor_basic`` had a test for built-in functions that was commented out because Matlab eventually didn't distinguish (if I recall correctly).  It looks like python does, so you may need a few more conditionals.  

You can add an error output if none of the expected conditional pass (built-in function, user defined function, string).

Please make sure you understand what is being programmed. The exact same functionality should be performed.  Test scripts only test for correctness of implementation, not for the full flexibility of implementation.  Please do not forget that. The tests being correct usually mean that permissible variation will also be correct.

**Comment by pv33** [comment]
Note that Matlab's ``exist`` function performs multiple tests per [documentation](https://www.mathworks.com/help/matlab/ref/exist.html).  The tests will most likely be reproduced as individual conditional statement in python. Per the documentation the ``exist`` outputs in [2, 3, 5, 6] test for:

```
0 — name does not exist or cannot be found for other reasons. For example, if name exists in a restricted folder to which MATLAB® does not have access, exist returns 0.
1 — name is a variable in the workspace.
2 — name is a file with extension .m, .mlx, or .mlapp, or name is the name of a file with a non-registered file extension (.mat, .fig, .txt).
3 — name is a MEX-file on your MATLAB search path.
4 — name is a loaded Simulink® model or a Simulink model or library file on your MATLAB search path.
5 — name is a built-in MATLAB function. This does not include classes.
6 — name is a P-code file on your MATLAB search path.
7 — name is a folder.
8 — name is a class. (exist returns 0 for Java classes if you start MATLAB with the -nojvm option.)
```

p-code is compiled Matlab code with a Matlab invocation wrapper. It would be equivalent to compiled python code.  It may or may not be possible to do and to test for in python.  Please do make sure you understand what you are doing by reading the documentation of functions that you do not understand, then making an effort to establish the proper python equivalent.

mex code is C/C++ compiled code that is capable of running in Matlab due to having been written with a Matlab invocation wrapper. Not sure what python equivalent is.

Both of the compiled function tests can be ignored for now if you are not certain.  Just add to comments that they are missing. Possibly by adding an @note or @todo into the function doxygen tags before the function definition.

**Comment by Uio96** [comment]
Have fixed the issues according to your instructions. Leave compiled function tests for further development.

**Comment by pv33** [comment]
@Uio96 
I think the focus on the string arguments was a bit too heavy and undermined the intent behind the improcessor classes.  Most of the time I would use it I actually would pass the function pointer, but the documented parts did not discuss that.  

Using string arguments is a bad idea in python because of the way modules and packages work. Matlab behaves differently.

After talking to another student and mentioning that the most important part was a lambda-type functionality, I've removed the string parsing parts and moved strictly to function pointers. The nice thing about function pointers is that import scoping is more relaxed.  As long as the invocation has access to the functions, they can be passed in. There is no need to import within the class proper, which was an important constraint.

The test scripts should work for you.  Please let me know if they do not.

Also, we'll have to discuss how to design execute.  My brother recommends virtual environments. The other student, Varun, also recommended using the ``requirements.txt`` file possible to put into modules. I'll be exploring those options in the coming days.

Meanwhile, I think a major psychological milestone on my part has been realized.  I feel a bit more comfortable but am still concerned about progress. I also need to upgrade to 20.04 (currently using 16.04, which does not get up to your python3 version).

**Comment by pv33** [comment]
Close this issue if things work or you can fix the problem. Respond if there is an unresolvable issue.

**Comment by Uio96** [comment]
> @Uio96
> I think the focus on the string arguments was a bit too heavy and undermined the intent behind the improcessor classes. Most of the time I would use it I actually would pass the function pointer, but the documented parts did not discuss that.
> 
> Using string arguments is a bad idea in python because of the way modules and packages work. Matlab behaves differently.
> 
> After talking to another student and mentioning that the most important part was a lambda-type functionality, I've removed the string parsing parts and moved strictly to function pointers. The nice thing about function pointers is that import scoping is more relaxed. As long as the invocation has access to the functions, they can be passed in. There is no need to import within the class proper, which was an important constraint.
> 
> The test scripts should work for you. Please let me know if they do not.
> 
> Also, we'll have to discuss how to design execute. My brother recommends virtual environments. The other student, Varun, also recommended using the `requirements.txt` file possible to put into modules. I'll be exploring those options in the coming days.
> 
> Meanwhile, I think a major psychological milestone on my part has been realized. I feel a bit more comfortable but am still concerned about progress. I also need to upgrade to 20.04 (currently using 16.04, which does not get up to your python3 version).

I agree with the idea to use `requirements.txt`. It is a popular idea when using Python. Users can easily set up a new environment by pip.

Thank you so much for the great help today. I will keep working on the code stuff to solve the GitHub issues. Probably I will make more progress this weekend after the meeting with NVIDIA people tomorrow.

**Comment by Uio96** [comment]
> Close this issue if things work or you can fix the problem. Respond if there is an unresolvable issue.

Have fixed the typos and the testing scripts are functional now.
